swagger: "2.0"

info:
  version: 0.0.2
  title: MySkills-API
  description: An API to authorise mobile clients against third party APIs and fetch bearer web tokens.

schemes:
  - https
host: ms-dev.anyapi.de
basePath: /

paths:
  /authentication:
    post:
      summary: Authenticate against myskills-api
      description: Returns a User ID and a Web Token
      
      parameters:
        - name: person
          in: body
          description: The person to create.
          schema:
            required:
              - email
              - password
              - strategy
            properties:
              email:
                type: string
              password:
                type: string
              strategy:
                type: string
    
      responses:
        401:
          description: Unauthorized
        200:
          description: Authorisation Data from Myskills API
          schema:
            type: object
            properties:
              accessToken:
                type: string
              user:
                type: object
                properties:
                  id: 
                    type: string
             
                  
  /remote:
    get:
      summary: Authenticate against chino-api App/Client
      description: Returns a User ID and a Web Token
      
      parameters:
        - name: person
          in: body
          description: The person to create.
          schema:
            required:
              - email
              - password
              - strategy
            properties:
              email:
                type: string
              password:
                type: string
              strategy:
                type: string
    
      responses:
        401:
          description: Unauthorized
        200:
          description: Authorisation Data from Myskills API
          schema:
            type: object
            properties:
              accessToken:
                type: string
              user:
                type: object
                properties:
                  id: 
                    type: string
             
                  
                  
                    
                  
