swagger: "2.0"
info:
  version: 0.0.2
  title: MySkills-API
  description: An API to authorise mobile clients against third party APIs and fetch bearer web tokens.
schemes:
  - https
host: ms-dev.anyapi.de
basePath: /
paths:
  /authentication:
    post:
      summary: Authenticate app against myskills-api
      description: Returns a User ID and a Web Token
      parameters:
        - name: app
          in: body
          description: The myskills app credentials
          schema:
            required:
              - email
              - password
              - strategy
            properties:
              email:
                type: string
              password:
                type: string
              strategy:
                type: string
      responses:
        200:
          description: Authorisation Data for Myskills API
          schema:
            type: object
            properties:
              accessToken:
                type: string
              user:
                type: object
                properties:
                  id:
                    type: string
        401:
          description: Unauthorized
  /remote:
     get:
      summary: Get List of _ids for Remote Auth
      description: Returns a List of _ids from Myskills API
      parameters:
        - name: token
          in: header
          description: Provide the MySkills Web Token as an bearer token in authorization header
          required: true
          type: string
      responses:
        200:
          description: Authorisation Data proxied via Myskills API
          schema:
            type: array
            items:
              type: object
              properties:
                _id:
                  type: string
        401:
          description: Unauthorized
  /remote/{_id}:
    get:
      summary: Authenticate against Chino API
      description: Returns a Web Token, Refresh Token and permissions scope.
      
      parameters:
        - name: _id
          in: path
          required: true
          description: The user's id.
          type: string
        - name: token
          in: header
          description: Provide the MySkills Web Token as an bearer token in authorization header
          required: true
          type: string
      responses:
        200:
          description: Authorisation Data proxied via Myskills API
          schema:
            type: object
            properties:
              result:
                type: string
              result_code:
                type: integer
              data:
                type: object
                properties:
                  access_token: 
                    type: string
                  expires_in:
                    type: integer
                  token_type:
                    type: string
                  scope:
                    type: string
                  refresh_token:
                    type: string
        401:
          description: Unauthorized